### ISSUE TITLE
HPX theme removed Ligature Arrows

### ISSUE THREAD

**Issue by BrandonKMLee** [cannibalox/logseq-dark-hpx#5]
Currently, HPX removed the Ligature arrow `=>` From its font

For reference of what possible ligatures are there:
- https://github.com/tonsky/FiraCode
- https://github.com/microsoft/cascadia-code
- https://github.com/adobe-fonts/source-code-pro
- https://github.com/source-foundry/Hack

**Comment by cannibalox** [comment]
Ligatures should be enabled inside code blocks. Outside of code-blocks, the cairo and barlow font do not provide ligatures, but you can change the font family in the custom.css. 
I'm reworking the themes from the group up, not available atm, the updated ono-sendai theme will have ligatures everywhere (but it uses monospace font - JetBrains mono).
